apiVersion: batch/v1
kind: CronJob
metadata:
  name: distribute-cronjob
spec:
    schedule: "0 0 10 * *"
    successfulJobsHistoryLimit: 1
    failedJobsHistoryLimit: 1
    jobTemplate:
      spec:
        template:
          spec:
            containers:
            - name: distribute
              image: ${DOCKER_REGISTRY}/${IMAGE_NAME_DISTRIBUTE}:${VERSION}
              imagePullPolicy: IfNotPresent
              command: [ "node" ]
              args: [ "/app/src/index.js" ]
              env:
                - name: EOS_API_ENDPOINT
                  value: "${EOS_API_ENDPOINT}"
                - name: EOS_API_CHAIN_ID
                  value: "${EOS_API_CHAIN_ID}"
                - name: EOS_DISTRIBUTE_ACCOUNT
                  value: "${EOS_DISTRIBUTE_ACCOUNT}"
                - name: EOS_DISTRIBUTE_PERMISSION
                  value: "${EOS_DISTRIBUTE_PERMISSION}"
                - name: EOS_DISTRIBUTE_PRIVATE_KEY
                  value: "${EOS_DISTRIBUTE_PRIVATE_KEY}"
                - name: EOS_DISTRIBUTE_MAX_STEPS
                  value: "${EOS_DISTRIBUTE_MAX_STEPS}"
                - name: EOS_EDEN_ACCOUNT
                  value: "${EOS_EDEN_ACCOUNT}"
            restartPolicy: Never
